import {
  BalanceActiveIcon,
  BalanceIcon,
  ClansActiveIcon,
  ClansIcon,
  CraftActiveIcon,
  CraftIcon,
  FeaturesActiveIcon,
  FeaturesIcon,
  InterfaceActiveIcon,
  InterfaceIcon,
  MainInfoActiveIcon,
  MainInfoIcon,
  OlympActiveIcon,
  OlympIcon,
  RaidActiveIcon,
  RaidIcon,
  SealsActiveIcon,
  SealsIcon,
} from '../../../assets/images';

export const wikiNavData = [
  { key: 'mainInfoHeader', icon: MainInfoIcon, activeIcon: MainInfoActiveIcon },
  { key: 'starterKitHeader', icon: MainInfoIcon, activeIcon: MainInfoActiveIcon },
  {
    key: 'rewardsForTasksHeader',
    icon: OlympIcon,
    activeIcon: OlympActiveIcon,
  },
  {
    key: 'newUniqueTasksHeader',
    icon: MainInfoIcon,
    activeIcon: MainInfoActiveIcon,
  },
  {
    key: 'rewardsSeasonPassHeader',
    icon: OlympIcon,
    activeIcon: OlympActiveIcon,
  },
  {
    key: 'rewardsCalendarHeader',
    icon: OlympIcon,
    activeIcon: OlympActiveIcon,
  },
  {
    key: 'achievementBoxesRewardsHeader',
    icon: OlympIcon,
    activeIcon: OlympActiveIcon,
  },
  {
    key: 'autoHuntingHeader',
    icon: RaidIcon,
    activeIcon: RaidActiveIcon
  },
  { key: 'offlineHuntingHeader', icon: RaidIcon, activeIcon: RaidActiveIcon },
  { key: 'costumesHeader', icon: SealsIcon, activeIcon: SealsActiveIcon },
  { key: 'worldTradeHeader', icon: BalanceIcon, activeIcon: BalanceActiveIcon },
  { key: 'normalCreationHeader', icon: CraftIcon, activeIcon: CraftActiveIcon },
  { key: 'guaranteedEnhancementHeader', icon: CraftIcon, activeIcon: CraftActiveIcon },
  { key: 'questsHeader', icon: MainInfoIcon, activeIcon: MainInfoActiveIcon },
  {
    key: 'interfaceHeader',
    icon: InterfaceIcon,
    activeIcon: InterfaceActiveIcon,
  },
  {
    key: 'gameAssistantHeader',
    icon: InterfaceIcon,
    activeIcon: InterfaceActiveIcon,
  },
  { key: 'locationsAndHuntingZonesHeader', icon: RaidIcon, activeIcon: RaidActiveIcon },
  { key: 'olympiadHeader', icon: FeaturesIcon, activeIcon: FeaturesActiveIcon },
  { key: 'lCoinDropSystemHeader', icon: RaidIcon, activeIcon: RaidActiveIcon },
  { key: 'dropFrom90PlusMobsHeader', icon: RaidIcon, activeIcon: RaidActiveIcon },
  { key: 'clanBonusesHeader', icon: ClansIcon, activeIcon: ClansActiveIcon },
  { key: 'treasureChestHeader', icon: OlympIcon, activeIcon: OlympActiveIcon },
];
